### ISSUE TITLE
Fix vote on forum

### ISSUE THREAD

**Issue by Alerion** [RaD/djbookru#257]
```
Internal Server Error: /forum/vote/post/20060/
Traceback (most recent call last):
  File "/home/django/djbookru/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/django/djbookru/src/forum/views.py", line 326, in vote
    'voted': voted
  File "/home/django/djbookru/src/utils/views.py", line 33, in __init__
    status=status
  File "/home/django/djbookru/env/lib/python2.7/site-packages/django/http/response.py", line 318, in __init__
    super(HttpResponse, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'mimetype'
```

**Comment by and-nothing-else** [comment]
починено же! eaca5fa9914a20066ceafffad10b3897756f3052
